# This is an addition to ci/environment.yml, which upgrades dask to the git tip.
channels:
  - conda-forge
dependencies:
  - pip:
    - git+https://github.com/dask/dask
    - git+https://github.com/fjetter/distributed@all_comm_for_register_worker_plugin
    - git+https://github.com/dask/zict
