name: Conda build
on:
  push:

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: conda-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  conda:
    name: Build (and upload)
    runs-on: ${{ matrix.os }}
    # Required shell entrypoint to have properly activated conda environments
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.9"]
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: true
          channels: conda-forge
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          mamba install boa conda-verify pytest 

      - name: Build conda package
        run: |
          conda mambabuild recipe \
                --output-folder dist/conda \
                --no-anaconda-upload 

      - name: Install distribution
        run: |
          mamba install -c ./dist/conda coiled-distribution

      - name: Run tests
        run: pytest -v tests